set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

# find_program(ARM_GCC_PATH "arm-none-eabi-gcc")
# get_filename_component(TOOLCHAIN_PATH "${ARM_GCC_PATH}" DIRECTORY)

set(TOOLCHAIN_PATH "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/")
set(TARGET_BIN "arm-none-eabi")

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PATH}/${TARGET_BIN}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/${TARGET_BIN}-g++")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PATH}/${TARGET_BIN}-gcc")
set(CMAKE_OBJCOPY      "${TOOLCHAIN_PATH}/${TARGET_BIN}-objcopy")
set(CMAKE_SIZE         "${TOOLCHAIN_PATH}/${TARGET_BIN}-size")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
